# Generated by Django 5.1.2 on 2025-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_training_pdf_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
